-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 02:44:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema relsis_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema relsis_db
-- -----------------------------------------------------

DROP DATABASE IF EXISTS `relsis_db`;
CREATE DATABASE `relsis_db`;
USE `relsis_db`;

-- -----------------------------------------------------
-- Table `relsis_db`.`Component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Component` (
  `component_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `unit_measurement` VARCHAR(45) NOT NULL,
  `technical_info` VARCHAR(45) NULL,
  PRIMARY KEY (`component_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Device` (
  `device_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `supply_voltage` VARCHAR(45) NULL,
  `border_regulation_time` VARCHAR(45) NULL,
  `rating` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Component_Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Component_Device` (
  `component_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`component_id`, `device_id`),
  INDEX `fk_Component_Device_Component_idx` (`component_id` ASC),
  INDEX `fk_Component_Device_Device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_Component_Device_Component`
    FOREIGN KEY (`component_id`)
    REFERENCES `relsis_db`.`Component` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Component_Device_Device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `relsis_db`.`Device` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Client` (
  `client_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `contactPIB` VARCHAR(45) NOT NULL,
  `codeERPOU` VARCHAR(45) NULL,
  `code_taxpayer` VARCHAR(45) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Provider` (
  `provider_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `codeERPOU` VARCHAR(45) NULL,
  `code_taxpayer` VARCHAR(45) NULL,
  `contactPIB` VARCHAR(45) NOT NULL,
  `specialization` ENUM('конденсатор', 'діод', 'резістор', 'чіп', 'індуктивність', 'ящик') NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Order` (
  `order_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `startdate` VARCHAR(45) NOT NULL,
  `paid` TINYINT NOT NULL,
  PRIMARY KEY (`order_id`, `client_id`),
  INDEX `fk_Order_Client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `relsis_db`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Delivery` (
  `delivery_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `startdate` VARCHAR(45) NOT NULL,
  `paid` TINYINT NOT NULL,
  PRIMARY KEY (`delivery_id`, `provider_id`),
  INDEX `fk_Delivery_Provider1_idx` (`provider_id` ASC),
  CONSTRAINT `fk_Delivery_Provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `relsis_db`.`Provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Delivery_Component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Delivery_Component` (
  `delivery_id` INT NOT NULL,
  `component_id` INT NOT NULL,
  `number` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`delivery_id`, `component_id`),
  INDEX `fk_Delivery_Component_Delivery1_idx` (`delivery_id` ASC),
  INDEX `fk_Delivery_Component_Component1_idx` (`component_id` ASC),
  CONSTRAINT `fk_Delivery_Component_Delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `relsis_db`.`Delivery` (`delivery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_Component_Component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `relsis_db`.`Component` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relsis_db`.`Order_Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relsis_db`.`Order_Device` (
  `device_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `number` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`device_id`, `order_id`),
  INDEX `fk_Order_Device_Device1_idx` (`device_id` ASC),
  INDEX `fk_Order_Device_Order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_Order_Device_Device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `relsis_db`.`Device` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Device_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `relsis_db`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
